name = "blackteckel/job_assignment"
version = "1.0.0"
description = "Job assignment smart contract for job board"
license = "MIT"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"